// =======================================
// I18N ENGINE - Arabic / Français / English
// =======================================
const I18N = {
  ar: {
    "لوحة التحكم":"لوحة التحكم","معلومات الزبون":"معلومات الزبون","معلومات العميل":"معلومات العميل","الفني":"الفني","معلومات الفني":"معلومات الفني","المعالج":"المعالج","كارت الشاشة":"كارت الشاشة","الرام":"الرام","التخزين":"التخزين","اللوحة الأم":"اللوحة الأم","مزود الطاقة":"مزود الطاقة","التبريد":"التبريد","الهيكل":"الهيكل","الشاشة":"الشاشة","البطارية":"البطارية","المنافذ":"المنافذ","الشبكة":"الشبكة","الصور":"الصور","قائمة الفحص":"قائمة الفحص","ملاحظات عامة":"ملاحظات عامة","النتيجة النهائية":"النتيجة النهائية","إنشاء PDF":"إنشاء PDF","مسح التقرير":"مسح التقرير","تم الحفظ":"تم الحفظ","تقرير فحص الجهاز":"تقرير فحص الجهاز","PC Inspection Report":"PC Inspection Report","اسم الزبون":"اسم الزبون","اسم الفني":"اسم الفني","التخزين":"التخزين",
    "أدخل بيانات العميل الأساسية":"أدخل بيانات العميل الأساسية","أدخل بيانات الفني الذي يقوم بالفحص":"أدخل بيانات الفني الذي يقوم بالفحص","أدخل بيانات المعالج والتقييم":"أدخل بيانات المعالج والتقييم","أدخل معلومات بطاقة الرسومات":"أدخل معلومات بطاقة الرسومات","أدخل معلومات الذاكرة العشوائية":"أدخل معلومات الذاكرة العشوائية","أدخل معلومات وحدة التخزين":"أدخل معلومات وحدة التخزين","أدخل معلومات اللوحة الأم":"أدخل معلومات اللوحة الأم","أنشئ ملف PDF شاملًا للتقرير":"أنشئ ملف PDF شاملًا للتقرير",
    "اسم العميل":"اسم العميل","رقم الهاتف":"رقم الهاتف","اسم البائع":"اسم البائع","تاريخ التقرير":"تاريخ التقرير","نوع الجهاز":"نوع الجهاز","السيريال":"السيريال","ملاحظات العميل":"ملاحظات العميل","الشركة/المؤسسة":"الشركة/المؤسسة","الشركة / المؤسسة":"الشركة / المؤسسة","تاريخ الفحص":"تاريخ الفحص","ملاحظات الفني":"ملاحظات الفني","العلامة التجارية":"العلامة التجارية","العائلة":"العائلة","الموديل":"الموديل","الحالة":"الحالة","الحالة العامة":"الحالة العامة","ملاحظات":"ملاحظات","ملاحظات المعالج":"ملاحظات المعالج","سعة الذاكرة":"سعة الذاكرة","درجة الحرارة":"درجة الحرارة","درجة الحرارة °C":"درجة الحرارة °C","ملاحظات كارت الشاشة":"ملاحظات كارت الشاشة","السعة":"السعة","النوع":"النوع","السرعة":"السرعة","ملاحظات الرام":"ملاحظات الرام","الحالة الصحية":"الحالة الصحية","نسبة الصحة %":"نسبة الصحة %","ملاحظات التخزين":"ملاحظات التخزين","الشيبست":"الشيبست","Chipset":"Chipset","الشكل":"الشكل","Form Factor":"Form Factor","ملاحظات اللوحة الأم":"ملاحظات اللوحة الأم","القدرة":"القدرة","الشهادة":"الشهادة","ملاحظات مزود الطاقة":"ملاحظات مزود الطاقة","نوع التبريد":"نوع التبريد","ملاحظات التبريد":"ملاحظات التبريد","ملاحظات الهيكل":"ملاحظات الهيكل","Panel":"Panel","الدقة":"الدقة","الحجم":"الحجم","ملاحظات الشاشة":"ملاحظات الشاشة","الصحة":"الصحة","ملاحظات البطارية":"ملاحظات البطارية","المنافذ المتوفرة":"المنافذ المتوفرة","ملاحظات المنافذ":"ملاحظات المنافذ","Wi-Fi":"Wi-Fi","Ethernet":"Ethernet","ملاحظات الشبكة":"ملاحظات الشبكة","الملاحظات العامة":"الملاحظات العامة",
    "اختر الحالة":"اختر الحالة","اختر الحالة العامة":"اختر الحالة العامة","اختر العلامة التجارية":"اختر العلامة التجارية","اختر العائلة":"اختر العائلة","اختر الموديل":"اختر الموديل","اختر سعة الذاكرة":"اختر سعة الذاكرة","اختر السرعة":"اختر السرعة","اختر السعة":"اختر السعة","اختر النوع":"اختر النوع","اختر الشيبست":"اختر الشيبست","اختر الشكل":"اختر الشكل","اختر القدرة":"اختر القدرة","اختر نوع التبريد":"اختر نوع التبريد","اسحب الصور هنا أو اضغط للاختيار":"اسحب الصور هنا أو اضغط للاختيار","لم يتم إضافة صور بعد":"لم يتم إضافة صور بعد",
    "ممتاز":"ممتاز","جيد":"جيد","متوسط":"متوسط","يحتاج صيانة":"يحتاج صيانة","معطوب":"معطوب","سليم":"سليم","تحذير":"تحذير","فشل":"فشل","ممتازة":"ممتازة","جيدة":"جيدة","ضعيفة":"ضعيفة","لا تشحن":"لا تشحن","لا يوجد":"لا يوجد","بدون شهادة":"بدون شهادة","إنشاء PDF":"إنشاء PDF","تم إنشاء ملف PDF بنجاح":"تم إنشاء ملف PDF بنجاح","فشل إنشاء ملف PDF":"فشل إنشاء ملف PDF","تم إنشاء التقرير من PC Report System":"تم إنشاء التقرير من PC Report System","تمت إضافة":"تمت إضافة","صورة":"صورة","العميل":"العميل","قائمة الفحص":"قائمة الفحص","الصور":"الصور","أدخل معلومات مزود الطاقة":"أدخل معلومات مزود الطاقة","أدخل معلومات نظام التبريد":"أدخل معلومات نظام التبريد","أدخل معلومات الهيكل":"أدخل معلومات الهيكل","نوع الهيكل":"نوع الهيكل","اختر نوع الهيكل":"اختر نوع الهيكل","أدخل معلومات الشاشة":"أدخل معلومات الشاشة","اللوحة":"اللوحة","اختر الحجم":"اختر الحجم","اختر نوع اللوحة":"اختر نوع اللوحة","أدخل معلومات البطارية":"أدخل معلومات البطارية","أدخل المنافذ المتوفرة":"أدخل المنافذ المتوفرة","أدخل معلومات الشبكة":"أدخل معلومات الشبكة","اختر نوع الواي فاي":"اختر نوع الواي فاي","اختر سرعة الشبكة":"اختر سرعة الشبكة","اكتب أي ملاحظات أو ملاحظات إضافية":"اكتب أي ملاحظات أو ملاحظات إضافية","اختر الشهادة":"اختر الشهادة"
  },
  fr: {
    "لوحة التحكم":"Tableau de bord","معلومات الزبون":"Informations client","معلومات العميل":"Informations client","الفني":"Technicien","معلومات الفني":"Informations du technicien","المعالج":"Processeur","كارت الشاشة":"Carte graphique","الرام":"RAM","التخزين":"Stockage","اللوحة الأم":"Carte mère","مزود الطاقة":"Alimentation (PSU)","التبريد":"Refroidissement","الهيكل":"Boîtier","الشاشة":"Écran","البطارية":"Batterie","المنافذ":"Ports","الشبكة":"Réseau","الصور":"Photos","قائمة الفحص":"Checklist","ملاحظات عامة":"Notes générales","النتيجة النهائية":"Résultat final","إنشاء PDF":"Créer un PDF","مسح التقرير":"Effacer le rapport","تم الحفظ":"Enregistré","تقرير فحص الجهاز":"Rapport d'inspection","PC Inspection Report":"Rapport d'inspection PC","اسم الزبون":"Nom du client","اسم الفني":"Nom du technicien","التخزين":"Stockage",
    "أدخل بيانات العميل الأساسية":"Saisissez les informations de base du client","أدخل بيانات الفني الذي يقوم بالفحص":"Saisissez les informations du technicien","أدخل بيانات المعالج والتقييم":"Saisissez les informations et l'état du processeur","أدخل معلومات بطاقة الرسومات":"Saisissez les informations de la carte graphique","أدخل معلومات الذاكرة العشوائية":"Saisissez les informations de la mémoire RAM","أدخل معلومات وحدة التخزين":"Saisissez les informations du stockage","أدخل معلومات اللوحة الأم":"Saisissez les informations de la carte mère","أنشئ ملف PDF شاملًا للتقرير":"Générez un rapport PDF complet",
    "اسم العميل":"Nom du client","رقم الهاتف":"Téléphone","اسم البائع":"Nom du vendeur","تاريخ التقرير":"Date du rapport","نوع الجهاز":"Type d'appareil","السيريال":"Numéro de série","ملاحظات العميل":"Notes du client","الشركة/المؤسسة":"Entreprise / établissement","الشركة / المؤسسة":"Entreprise / établissement","تاريخ الفحص":"Date d'inspection","ملاحظات الفني":"Notes du technicien","العلامة التجارية":"Marque","العائلة":"Famille","الموديل":"Modèle","الحالة":"État","الحالة العامة":"État général","ملاحظات":"Notes","ملاحظات المعالج":"Notes du processeur","سعة الذاكرة":"Mémoire VRAM","درجة الحرارة":"Température","درجة الحرارة °C":"Température °C","ملاحظات كارت الشاشة":"Notes de la carte graphique","السعة":"Capacité","النوع":"Type","السرعة":"Vitesse","ملاحظات الرام":"Notes de la RAM","الحالة الصحية":"État de santé","نسبة الصحة %":"Santé %","ملاحظات التخزين":"Notes du stockage","الشيبست":"Chipset","Chipset":"Chipset","الشكل":"Format","Form Factor":"Format","ملاحظات اللوحة الأم":"Notes de la carte mère","القدرة":"Puissance","الشهادة":"Certification","ملاحظات مزود الطاقة":"Notes de l'alimentation","نوع التبريد":"Type de refroidissement","ملاحظات التبريد":"Notes du refroidissement","ملاحظات الهيكل":"Notes du boîtier","Panel":"Dalle","الدقة":"Résolution","الحجم":"Taille","ملاحظات الشاشة":"Notes de l'écran","الصحة":"Santé","ملاحظات البطارية":"Notes de la batterie","المنافذ المتوفرة":"Ports disponibles","ملاحظات المنافذ":"Notes des ports","Wi-Fi":"Wi-Fi","Ethernet":"Ethernet","ملاحظات الشبكة":"Notes réseau","الملاحظات العامة":"Notes générales",
    "اختر الحالة":"Sélectionnez l'état","اختر الحالة العامة":"Sélectionnez l'état général","اختر العلامة التجارية":"Sélectionnez la marque","اختر العائلة":"Sélectionnez la famille","اختر الموديل":"Sélectionnez le modèle","اختر سعة الذاكرة":"Sélectionnez la mémoire","اختر السرعة":"Sélectionnez la vitesse","اختر السعة":"Sélectionnez la capacité","اختر النوع":"Sélectionnez le type","اختر الشيبست":"Sélectionnez le chipset","اختر الشكل":"Sélectionnez le format","اختر القدرة":"Sélectionnez la puissance","اختر نوع التبريد":"Sélectionnez le type de refroidissement","اسحب الصور هنا أو اضغط للاختيار":"Glissez les images ici ou cliquez pour sélectionner","لم يتم إضافة صور بعد":"Aucune photo ajoutée",
    "ممتاز":"Excellent","جيد":"Bon","متوسط":"Moyen","يحتاج صيانة":"À réparer","معطوب":"Défectueux","سليم":"Sain","تحذير":"Avertissement","فشل":"Échec","ممتازة":"Excellente","جيدة":"Bonne","ضعيفة":"Faible","لا تشحن":"Ne charge pas","لا يوجد":"Aucun","بدون شهادة":"Sans certification","تم إنشاء ملف PDF بنجاح":"PDF créé avec succès","فشل إنشاء ملف PDF":"Échec de création du PDF","تم إنشاء التقرير من PC Report System":"Rapport généré par PC Report System","تمت إضافة":"Ajout de","صورة":"photo","العميل":"Client","أدخل معلومات مزود الطاقة":"Saisissez les informations de l'alimentation","أدخل معلومات نظام التبريد":"Saisissez les informations du refroidissement","أدخل معلومات الهيكل":"Saisissez les informations du boîtier","نوع الهيكل":"Type de boîtier","اختر نوع الهيكل":"Sélectionnez le type de boîtier","أدخل معلومات الشاشة":"Saisissez les informations de l'écran","اللوحة":"Dalle","اختر الحجم":"Sélectionnez la taille","اختر نوع اللوحة":"Sélectionnez la dalle","أدخل معلومات البطارية":"Saisissez les informations de la batterie","أدخل المنافذ المتوفرة":"Saisissez les ports disponibles","أدخل معلومات الشبكة":"Saisissez les informations réseau","اختر نوع الواي فاي":"Sélectionnez le Wi-Fi","اختر سرعة الشبكة":"Sélectionnez la vitesse réseau","اكتب أي ملاحظات أو ملاحظات إضافية":"Écrivez des notes ou remarques supplémentaires","اختر الشهادة":"Sélectionnez la certification","مبرد هواء أصلي":"Ventirad d'origine","مبرد هواء خارجي":"Ventirad externe","تبريد مائي AIO":"Watercooling AIO","تبريد مائي مخصص":"Watercooling custom","بدون شهادة":"Sans certification","15.6 بوصة":"15,6 pouces","19 بوصة":"19 pouces","21.5 بوصة":"21,5 pouces","24 بوصة":"24 pouces","27 بوصة":"27 pouces","32 بوصة":"32 pouces","HD 1366x768":"HD 1366x768","Full HD 1920x1080":"Full HD 1920x1080","2K 2560x1440":"2K 2560x1440","4K 3840x2160":"4K 3840x2160","ممتازة":"Excellente","جيدة":"Bonne","ضعيفة":"Faible","لا تشحن":"Ne charge pas","WiFi 4 (802.11n)":"WiFi 4 (802.11n)","WiFi 5 (802.11ac)":"WiFi 5 (802.11ac)","WiFi 6 (802.11ax)":"WiFi 6 (802.11ax)"
  },
  en: {
    "لوحة التحكم":"Dashboard","معلومات الزبون":"Customer Information","معلومات العميل":"Customer Information","الفني":"Technician","معلومات الفني":"Technician Information","المعالج":"Processor","كارت الشاشة":"Graphics Card","الرام":"RAM","التخزين":"Storage","اللوحة الأم":"Motherboard","مزود الطاقة":"Power Supply","التبريد":"Cooling","الهيكل":"Case","الشاشة":"Monitor","البطارية":"Battery","المنافذ":"Ports","الشبكة":"Network","الصور":"Photos","قائمة الفحص":"Checklist","ملاحظات عامة":"General Notes","النتيجة النهائية":"Final Result","إنشاء PDF":"Create PDF","مسح التقرير":"Clear Report","تم الحفظ":"Saved","تقرير فحص الجهاز":"Device Inspection Report","PC Inspection Report":"PC Inspection Report","اسم الزبون":"Customer Name","اسم الفني":"Technician Name","التخزين":"Storage",
    "أدخل بيانات العميل الأساسية":"Enter the customer's basic information","أدخل بيانات الفني الذي يقوم بالفحص":"Enter the technician's information","أدخل بيانات المعالج والتقييم":"Enter processor information and condition","أدخل معلومات بطاقة الرسومات":"Enter graphics card information","أدخل معلومات الذاكرة العشوائية":"Enter RAM information","أدخل معلومات وحدة التخزين":"Enter storage information","أدخل معلومات اللوحة الأم":"Enter motherboard information","أنشئ ملف PDF شاملًا للتقرير":"Generate a complete PDF report",
    "اسم العميل":"Customer Name","رقم الهاتف":"Phone Number","اسم البائع":"Seller Name","تاريخ التقرير":"Report Date","نوع الجهاز":"Device Type","السيريال":"Serial Number","ملاحظات العميل":"Customer Notes","الشركة/المؤسسة":"Company / Organization","الشركة / المؤسسة":"Company / Organization","تاريخ الفحص":"Inspection Date","ملاحظات الفني":"Technician Notes","العلامة التجارية":"Brand","العائلة":"Family","الموديل":"Model","الحالة":"Status","الحالة العامة":"Overall Status","ملاحظات":"Notes","ملاحظات المعالج":"Processor Notes","سعة الذاكرة":"Memory Capacity","درجة الحرارة":"Temperature","درجة الحرارة °C":"Temperature °C","ملاحظات كارت الشاشة":"Graphics Card Notes","السعة":"Capacity","النوع":"Type","السرعة":"Speed","ملاحظات الرام":"RAM Notes","الحالة الصحية":"Health","نسبة الصحة %":"Health %","ملاحظات التخزين":"Storage Notes","الشيبست":"Chipset","Chipset":"Chipset","الشكل":"Form Factor","Form Factor":"Form Factor","ملاحظات اللوحة الأم":"Motherboard Notes","القدرة":"Wattage","الشهادة":"Certification","ملاحظات مزود الطاقة":"Power Supply Notes","نوع التبريد":"Cooling Type","ملاحظات التبريد":"Cooling Notes","ملاحظات الهيكل":"Case Notes","Panel":"Panel","الدقة":"Resolution","الحجم":"Size","ملاحظات الشاشة":"Monitor Notes","الصحة":"Health","ملاحظات البطارية":"Battery Notes","المنافذ المتوفرة":"Available Ports","ملاحظات المنافذ":"Port Notes","Wi-Fi":"Wi-Fi","Ethernet":"Ethernet","ملاحظات الشبكة":"Network Notes","الملاحظات العامة":"General Notes",
    "اختر الحالة":"Select status","اختر الحالة العامة":"Select overall status","اختر العلامة التجارية":"Select brand","اختر العائلة":"Select family","اختر الموديل":"Select model","اختر سعة الذاكرة":"Select memory capacity","اختر السرعة":"Select speed","اختر السعة":"Select capacity","اختر النوع":"Select type","اختر الشيبست":"Select chipset","اختر الشكل":"Select form factor","اختر القدرة":"Select wattage","اختر نوع التبريد":"Select cooling type","اسحب الصور هنا أو اضغط للاختيار":"Drag images here or click to select","لم يتم إضافة صور بعد":"No photos added",
    "ممتاز":"Excellent","جيد":"Good","متوسط":"Average","يحتاج صيانة":"Needs Service","معطوب":"Damaged","سليم":"Healthy","تحذير":"Warning","فشل":"Failed","ممتازة":"Excellent","جيدة":"Good","ضعيفة":"Weak","لا تشحن":"Not Charging","لا يوجد":"None","بدون شهادة":"No Certification","تم إنشاء ملف PDF بنجاح":"PDF created successfully","فشل إنشاء ملف PDF":"Failed to create PDF","تم إنشاء التقرير من PC Report System":"Report generated by PC Report System","تمت إضافة":"Added","صورة":"photo","العميل":"Customer","أدخل معلومات مزود الطاقة":"Enter power supply information","أدخل معلومات نظام التبريد":"Enter cooling system information","أدخل معلومات الهيكل":"Enter case information","نوع الهيكل":"Case Type","اختر نوع الهيكل":"Select case type","أدخل معلومات الشاشة":"Enter monitor information","اللوحة":"Panel","اختر الحجم":"Select size","اختر نوع اللوحة":"Select panel type","أدخل معلومات البطارية":"Enter battery information","أدخل المنافذ المتوفرة":"Enter available ports","أدخل معلومات الشبكة":"Enter network information","اختر نوع الواي فاي":"Select Wi-Fi type","اختر سرعة الشبكة":"Select network speed","اكتب أي ملاحظات أو ملاحظات إضافية":"Write any notes or additional remarks","اختر الشهادة":"Select certification","مبرد هواء أصلي":"Stock air cooler","مبرد هواء خارجي":"Aftermarket air cooler","تبريد مائي AIO":"AIO liquid cooling","تبريد مائي مخصص":"Custom liquid cooling","بدون شهادة":"No Certification","15.6 بوصة":"15.6 inches","19 بوصة":"19 inches","21.5 بوصة":"21.5 inches","24 بوصة":"24 inches","27 بوصة":"27 inches","32 بوصة":"32 inches","HD 1366x768":"HD 1366x768","Full HD 1920x1080":"Full HD 1920x1080","2K 2560x1440":"2K 2560x1440","4K 3840x2160":"4K 3840x2160","ممتازة":"Excellent","جيدة":"Good","ضعيفة":"Weak","لا تشحن":"Not Charging","WiFi 4 (802.11n)":"WiFi 4 (802.11n)","WiFi 5 (802.11ac)":"WiFi 5 (802.11ac)","WiFi 6 (802.11ax)":"WiFi 6 (802.11ax)"
  }
};

const LANG_META = { ar:{name:"العربية", dir:"rtl"}, fr:{name:"Français", dir:"ltr"}, en:{name:"English", dir:"ltr"} };
let currentLang = localStorage.getItem("pc_report_language") || "ar";
if(!I18N[currentLang]) currentLang = "ar";

function t(text){
  if(text === undefined || text === null) return text;
  return (I18N[currentLang] && I18N[currentLang][text]) || text;
}
function setLanguage(lang){
  if(!I18N[lang]) return;
  currentLang = lang;
  localStorage.setItem("pc_report_language", lang);
  const meta = LANG_META[lang];
  document.documentElement.lang = lang;
  document.documentElement.dir = meta.dir;
  document.body.dir = meta.dir;
  const bootstrap = document.getElementById("bootstrapCss");
  if(bootstrap) bootstrap.href = lang === "ar" ? "https://cdn.jsdelivr.net/npm/bootstrap.rtl@5.3.8/dist/css/bootstrap.rtl.min.css" : "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css";
  const selector = document.getElementById("languageSelect");
  if(selector) selector.value = lang;
  translateDOM();
  if(typeof window.renderPage === "function" && typeof getCurrentPage === "function") window.renderPage(getCurrentPage());
}
function translateDOM(root=document.body){
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes=[];
  while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node=>{
    const raw=node.nodeValue;
    const trimmed=raw.trim();
    if(!trimmed || node.parentElement?.closest("script,style")) return;
    const translated=t(trimmed);
    if(translated!==trimmed) node.nodeValue=raw.replace(trimmed, translated);
  });
  root.querySelectorAll("input[placeholder],textarea[placeholder],option").forEach(el=>{
    if(el.tagName === "OPTION") el.textContent=t(el.textContent.trim());
    else el.placeholder=t(el.placeholder);
  });
}
function initLanguageSelector(){
  const selector=document.getElementById("languageSelect");
  if(!selector) return;
  selector.value=currentLang;
  selector.addEventListener("change",()=>setLanguage(selector.value));
  document.documentElement.lang=currentLang;
  document.documentElement.dir=LANG_META[currentLang].dir;
  document.body.dir=LANG_META[currentLang].dir;
  const bootstrap=document.getElementById("bootstrapCss");
  if(bootstrap) bootstrap.href=currentLang === "ar" ? "https://cdn.jsdelivr.net/npm/bootstrap.rtl@5.3.8/dist/css/bootstrap.rtl.min.css" : "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css";
  translateDOM();
}
window.t=t; window.setLanguage=setLanguage; window.translateDOM=translateDOM; window.getCurrentLanguage=()=>currentLang;
